all install clean: 
	$(MAKE) -C pam_unix $@
	$(MAKE) -C pam_securetty $@
	$(MAKE) -C pam_nologin $@
	$(MAKE) -C pam_shells $@
	$(MAKE) -C pam_wheel $@
	$(MAKE) -C pam_rootok $@
	$(MAKE) -C pam_permit $@
	$(MAKE) -C pam_deny $@

